"""Offline model-facing Hybrid Semantic IR contract and fake runner."""

from .contract import (
    FORBIDDEN_MODEL_TOKENS,
    MODEL_FACING_IR_CONTRACT_VERSION,
    ModelFacingContract,
    ModelFacingRequest,
    RequestSectionMetrics,
    build_model_facing_contract,
    build_model_facing_request,
)
from .projection import (
    GLOBAL_STRUCTURAL_TRIGGER_EVENTS,
    PROJECTION_SOURCES,
    SEMANTIC_ACTORS,
    SEMANTIC_INTENTS,
    EnumDomainProjection,
    HybridGenerationContext,
    ProjectionError,
    SemanticEnumProjection,
    project_semantic_enums,
)
from .runner import (
    FIRST_FAILURE_LAYERS,
    HYBRID_EVIDENCE_VERSION,
    HYBRID_EXPERIMENT,
    FakePipelineResult,
    FakeProvider,
    HybridEvidence,
    HybridExperimentIdentity,
    HybridSemanticIRRunner,
    SafeIRDiagnostics,
    run_fake_pipeline,
    validate_hybrid_evidence,
    write_evidence_atomic,
)

__all__ = [
    "EnumDomainProjection",
    "GLOBAL_STRUCTURAL_TRIGGER_EVENTS",
    "FIRST_FAILURE_LAYERS",
    "FORBIDDEN_MODEL_TOKENS",
    "FakePipelineResult",
    "FakeProvider",
    "HYBRID_EVIDENCE_VERSION",
    "HYBRID_EXPERIMENT",
    "HybridEvidence",
    "HybridExperimentIdentity",
    "HybridGenerationContext",
    "HybridSemanticIRRunner",
    "MODEL_FACING_IR_CONTRACT_VERSION",
    "ModelFacingContract",
    "ModelFacingRequest",
    "PROJECTION_SOURCES",
    "ProjectionError",
    "RequestSectionMetrics",
    "SEMANTIC_ACTORS",
    "SEMANTIC_INTENTS",
    "SafeIRDiagnostics",
    "SemanticEnumProjection",
    "build_model_facing_contract",
    "build_model_facing_request",
    "project_semantic_enums",
    "run_fake_pipeline",
    "validate_hybrid_evidence",
    "write_evidence_atomic",
]
