"""Interactive manual entry point for the frozen Skill Design v1 pipeline.

This module is deliberately a presentation/orchestration shell.  It reuses
the existing model-facing contract, runner, compiler, evaluator, and repair
session; it never writes formal benchmark evidence.
"""

# The direct-script sys.path bootstrap intentionally precedes project imports.
# ruff: noqa: I001

from __future__ import annotations

import argparse
import os
import sys
import uuid
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Callable, TextIO

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from character_intelligence.compiler import COMPILER_VERSION_V2  # noqa: E402
from character_intelligence.hybrid_ir.contract import build_model_facing_request  # noqa: E402
from character_intelligence.hybrid_ir.projection import (  # noqa: E402
    SEMANTIC_ACTORS,
    HybridGenerationContext,
)
from character_intelligence.hybrid_ir.language import (  # noqa: E402
    OUTPUT_LANGUAGE_CHOICES,
    resolve_output_language,
)
from character_intelligence.hybrid_ir.repair import (  # noqa: E402
    RepairOutcome,
    SemanticRepairResult,
    SemanticRepairSession,
)
from character_intelligence.hybrid_ir.runner import (  # noqa: E402
    FIRST_FAILURE_LAYERS,
    FakePipelineResult,
    HybridProvider,
    HybridProviderInvocationError,
    _default_hybrid_provider_factory,
    _identity,
    _run_pipeline,
)
from character_intelligence.planner import build_character_design_plan  # noqa: E402
from character_skill.contract import ABILITY_MODES  # noqa: E402
from character_skill.evaluation import _ROLE_ROWS  # noqa: E402
from combat_semantics import CANONICAL_COMBAT_ROLES  # noqa: E402


ROLE_CHOICES = tuple(CANONICAL_COMBAT_ROLES)
MODE_CHOICES = tuple(sorted(ABILITY_MODES))
DEFAULT_MODEL = "deepseek-v4-pro"

_ZH_ROLES = {
    "main_dps": "主输出",
    "sub_dps": "副输出",
    "support": "辅助",
    "healer": "治疗",
    "control": "控制",
    "defense": "防御",
}
_ZH_MODES = {"active": "主动", "passive": "被动", "reaction": "反应"}
_ZH_ACTORS = {
    "self": "自身",
    "ally": "队友",
    "enemy": "敌方",
    "scene": "场景",
    "summon": "召唤物",
    "team": "队伍",
}
_ZH_TRIGGER_EVENTS = {
    "ability_invoked": "技能调用",
    "action_completed": "行动完成",
    "damage_received": "受到伤害",
    "feedback_received": "收到反馈",
    "healing_received": "受到治疗",
    "resource_gained": "获得资源",
    "resource_spent": "消耗资源",
    "scene_entered": "进入场景",
    "scene_exited": "离开场景",
    "state_entered": "进入状态",
    "state_exited": "离开状态",
    "summon_acted": "召唤物行动",
    "summon_departed": "召唤物离场",
    "summon_spawned": "召唤物出现",
}
_ZH_FEEDBACK_EVENTS = {
    "effect_resolved": "效果生效",
    "resource_changed": "资源变化",
    "state_changed": "状态变化",
    "summon_changed": "召唤物变化",
}
_ZH_OPERATIONS = {
    "direct_output": "直接输出",
    "follow_up_output": "后续输出",
    "ally_enablement": "队友支援",
    "recover_or_mitigate": "恢复/缓解",
    "enemy_action_control": "敌方行动控制",
    "threat_protection": "威胁保护",
    "enables": "促成",
    "modifies": "修改",
    "terminates": "终止",
}
_ZH_LABELS = {
    "title": "技能设计结果",
    "role": "角色定位",
    "mode": "技能模式",
    "name": "技能名称",
    "trigger": "触发方式",
    "effect": "核心效果",
    "feedback": "反馈 / 后续",
    "evaluator": "评估结果",
    "repair": "修复",
    "pipeline": "流水线",
    "safe_debug": "安全调试",
    "none": "无",
    "not_generated": "当前流水线未生成",
    "not_reached": "未到达",
    "unspecified": "未指定",
}
_ZH_EVALUATOR_STATUS = {"PASS": "通过", "FAIL": "失败", "NOT_REACHED": "未到达"}
_ZH_REPAIR_STATUS = {
    "NOT_NEEDED": "无需修复",
    "NOT_ATTEMPTED": "未尝试",
    "UNAVAILABLE": "不可用",
    "SUCCESS": "成功",
    "FAILED": "失败",
}


def _display_value(value: str, language: str, translations: dict[str, str]) -> str:
    return translations.get(value, value) if language == "zh-CN" else value


def _label(key: str, language: str) -> str:
    return _ZH_LABELS.get(key, key) if language == "zh-CN" else {
        "title": "Skill Design Result",
        "role": "Role",
        "mode": "Mode",
        "name": "Skill Name",
        "trigger": "Trigger",
        "effect": "Core Effect",
        "feedback": "Feedback / Continuation",
        "evaluator": "Evaluator",
        "repair": "Repair",
        "pipeline": "Pipeline",
        "safe_debug": "Safe debug",
        "none": "<none>",
        "not_generated": "<not generated by current pipeline>",
        "not_reached": "<not reached>",
        "unspecified": "<unspecified>",
    }.get(key, key)


@dataclass(frozen=True)
class PlaygroundExecution:
    """In-memory result of one manual generation and optional repair."""

    initial: FakePipelineResult
    final: FakePipelineResult
    repair: SemanticRepairResult | None
    repair_status: str


def _role_row(role: str) -> dict[str, object]:
    if role not in ROLE_CHOICES:
        raise ValueError("unsupported role")
    return _ROLE_ROWS[role]


def build_playground_context(role: str, mode: str, requirement: str) -> HybridGenerationContext:
    """Build a v2 context from user-owned inputs, without case lookup."""

    if role not in ROLE_CHOICES or mode not in MODE_CHOICES:
        raise ValueError("role and mode must use authoritative vocabulary")
    if not isinstance(requirement, str) or not requirement.strip():
        raise ValueError("requirement must be non-empty")

    brief = (
        f"Design a {role} {mode} skill.\n"
        f"User requirement:\n{requirement.strip()}"
    )
    plan = build_character_design_plan(brief)
    row = _role_row(role)
    triggers = row["triggers"]
    subjects = row["subjects"]
    assert isinstance(triggers, frozenset)
    assert isinstance(subjects, frozenset)
    allowed_events = tuple(sorted(event for _actor, event in triggers))
    return HybridGenerationContext(
        brief,
        plan=plan,
        case_id="manual-playground",
        contract_profile="generalization_v2",
        allowed_actors=SEMANTIC_ACTORS,
        allowed_trigger_subjects=(
            tuple(sorted({actor for actor, _event in triggers}))
            if mode != "passive"
            else None
        ),
        allowed_effect_subjects=tuple(sorted(subjects)),
        allowed_trigger_events=None if mode == "passive" else allowed_events,
        allowed_modes=(mode,),
        allowed_roles=(role,),
        allowed_centralities=("core",),
    )


def build_playground_evaluation_context(role: str, mode: str) -> dict[str, object]:
    """Build generic role/mode requirements from the authoritative evaluator row."""

    row = _role_row(role)
    duty = row["duty"]
    subjects = row["subjects"]
    triggers = row["triggers"]
    assert isinstance(duty, str)
    assert isinstance(subjects, frozenset)
    assert isinstance(triggers, frozenset)

    requirement: dict[str, object] = {
        "requirement_id": f"manual_{role}",
        "mechanic_kind": "passive" if mode == "passive" else "triggered",
        "effect": {
            "subject_kinds": sorted(subjects),
            "operations": [duty],
            "object_kinds": [],
        },
        "feedback": {"required": False, "events": [], "operations": []},
        "allowed_modes": [mode],
    }
    if mode != "passive":
        requirement["trigger"] = {
            "subject_kinds": sorted({actor for actor, _event in triggers}),
            "events": sorted({event for _actor, event in triggers}),
            "source_kinds": [],
        }
    return {
        "intent": {
            "mechanic_requirements": [requirement],
            "forbidden_mechanic_families": [],
            "hard_constraint_conflicts": [],
        },
        "combat_role_profile": {"primary_role": role, "secondary_roles": []},
        "reference_review_context": None,
    }


def run_manual_pipeline(
    provider: HybridProvider,
    context: HybridGenerationContext,
    evaluation_context: dict[str, object],
    *,
    model: str = DEFAULT_MODEL,
    language: str = "en",
    repo_root: Path = ROOT,
    invocation_id: str | None = None,
) -> FakePipelineResult:
    """Run the existing pipeline in memory under an independent manual identity."""

    from character_intelligence.semantic_ir.schema import SEMANTIC_IR_V2_VERSION

    selected_language = resolve_output_language(language, context.brief)
    request = build_model_facing_request(context, language=selected_language)
    identity = replace(
        _identity(
            repo_root,
            request.contract.digest,
            context.case_id,
            request.contract.version,
            context.context_projection_version,
            context.context_projection_digest,
            target_sample_count=1,
            experiment="manual-playground",
            ir_schema_version=SEMANTIC_IR_V2_VERSION,
            compiler_version=COMPILER_VERSION_V2,
        ),
        model=model,
    )
    result = _run_pipeline(
        provider,
        context,
        evaluation_context,
        repo_root=repo_root,
        sample_index=1,
        target_sample_count=1,
        experiment="manual-playground",
        identity=identity,
        language=selected_language,
    )
    manual_id = invocation_id or f"manual-playground-{uuid.uuid4().hex}"
    return replace(result, evidence=replace(result.evidence, run_id=manual_id))


def _manualize_result(result: FakePipelineResult, *, model: str) -> FakePipelineResult:
    """Keep any in-memory revalidation identity independent of formal runs."""

    return replace(
        result,
        evidence=replace(
            result.evidence,
            identity=replace(result.evidence.identity, model=model),
            run_id=f"manual-playground-{uuid.uuid4().hex}",
        ),
    )


def execute_playground(
    provider: HybridProvider,
    role: str,
    mode: str,
    requirement: str,
    *,
    model: str = DEFAULT_MODEL,
    language: str = "auto",
    repair_decider: Callable[[], bool] | None = None,
    repo_root: Path = ROOT,
) -> PlaygroundExecution:
    """Generate once and, only after confirmation, repair at most once."""

    selected_language = resolve_output_language(language, requirement)
    context = build_playground_context(role, mode, requirement)
    evaluation_context = build_playground_evaluation_context(role, mode)
    initial = run_manual_pipeline(
        provider,
        context,
        evaluation_context,
        model=model,
        language=selected_language,
        repo_root=repo_root,
    )
    evidence = initial.evidence
    if evidence.evaluator_outcome == "PASS":
        return PlaygroundExecution(initial, initial, None, "NOT_NEEDED")
    if evidence.first_failure_layer != "EVALUATOR" or evidence.evaluator_outcome != "FAIL":
        return PlaygroundExecution(initial, initial, None, "UNAVAILABLE")
    if repair_decider is None or not repair_decider():
        return PlaygroundExecution(initial, initial, None, "NOT_ATTEMPTED")

    session = SemanticRepairSession(
        initial,
        context,
        evaluation_context,
        language=selected_language,
        repo_root=str(repo_root),
    )
    repair = session.run(lambda request: provider.complete(request.to_prompt()))
    if repair.revalidation is not None:
        repair = replace(repair, revalidation=_manualize_result(repair.revalidation, model=model))
    final = repair.revalidation if repair.outcome is RepairOutcome.REPAIR_SUCCESS else initial
    if repair.outcome is RepairOutcome.REPAIR_SUCCESS:
        status = "SUCCESS"
    elif repair.outcome is RepairOutcome.REPAIR_UNAVAILABLE:
        status = "UNAVAILABLE"
    else:
        status = "FAILED"
    return PlaygroundExecution(initial, final, repair, status)


def _candidate_summary(
    result: FakePipelineResult,
    *,
    language: str = "en",
) -> tuple[str, str, str, str]:
    candidate = result.candidate
    if candidate is None or not candidate.entries:
        missing = _label("not_generated", language)
        not_reached = _label("not_reached", language)
        return (
            missing,
            not_reached,
            not_reached,
            not_reached,
        )
    entry = candidate.entries[0]
    trigger_parts: list[str] = []
    effect_parts: list[str] = []
    for protocol in entry.protocols:
        if protocol.when is not None:
            when = protocol.when
            subject = (
                _display_value(when.subject.kind, language, _ZH_ACTORS)
                if when.subject is not None
                else _label("unspecified", language)
            )
            event = _display_value(
                when.event or _label("unspecified", language),
                language,
                _ZH_TRIGGER_EVENTS,
            )
            trigger_parts.append(f"{subject} / {event}")
        for effect in protocol.causes:
            subject = (
                _display_value(effect.subject.kind, language, _ZH_ACTORS)
                if effect.subject is not None
                else _label("unspecified", language)
            )
            operation = _display_value(
                effect.operation or _label("unspecified", language),
                language,
                _ZH_OPERATIONS,
            )
            detail = effect.description.strip() or operation or _label("unspecified", language)
            detail_separator = "：" if language == "zh-CN" else ":"
            effect_parts.append(f"{subject} / {operation}{detail_separator} {detail}")
    feedback = (
        "; ".join(
            f"{_display_value(item.event, language, _ZH_FEEDBACK_EVENTS)} / "
            f"{_display_value(item.operation, language, _ZH_OPERATIONS)}"
            for item in candidate.feedback_relations
        )
        or (
            _label("none", language) + "（canonical result 未声明）"
            if language == "zh-CN"
            else "None declared by canonical result"
        )
    )
    return (
        entry.name.strip() or _label("not_generated", language),
        "; ".join(dict.fromkeys(trigger_parts)) or _label("none", language),
        "; ".join(dict.fromkeys(effect_parts)) or entry.display_text.strip() or _label("none", language),
        feedback,
    )


def _evaluator_label(result: FakePipelineResult) -> str:
    evidence = result.evidence
    if evidence.first_failure_layer is None and evidence.evaluator_outcome == "PASS":
        return "PASS"
    if evidence.first_failure_layer == "EVALUATOR":
        return "FAIL"
    return "NOT_REACHED"


def _stage_status(result: FakePipelineResult, stage: str) -> str:
    failure_layer = result.evidence.first_failure_layer
    if failure_layer is None:
        return "PASS"
    stage_index = FIRST_FAILURE_LAYERS.index(stage)
    failure_index = FIRST_FAILURE_LAYERS.index(failure_layer)
    if stage_index < failure_index:
        return "PASS"
    if stage_index == failure_index:
        return "FAIL"
    return "NOT_REACHED"


def render_result(
    execution: PlaygroundExecution,
    role: str,
    mode: str,
    *,
    language: str = "en",
    show_safe_debug: bool = False,
    provider: HybridProvider | None = None,
    output: TextIO = sys.stdout,
) -> None:
    """Print only selected canonical fields and bounded diagnostics."""

    result = execution.final
    name, trigger, effect, feedback = _candidate_summary(result, language=language)
    colon = "：" if language == "zh-CN" else ":"
    print(f"=== {_label('title', language)} ===", file=output)
    print(f"{_label('role', language)}{colon} {_display_value(role, language, _ZH_ROLES)}", file=output)
    print(f"{_label('mode', language)}{colon} {_display_value(mode, language, _ZH_MODES)}", file=output)
    print(f"{_label('name', language)}{colon} {name}", file=output)
    print(f"{_label('trigger', language)}{colon}", file=output)
    print(f"  {trigger}", file=output)
    print(f"{_label('effect', language)}{colon}", file=output)
    print(f"  {effect}", file=output)
    print(f"{_label('feedback', language)}{colon}", file=output)
    print(f"  {feedback}", file=output)
    evaluator = _evaluator_label(result)
    if language == "zh-CN":
        evaluator = _ZH_EVALUATOR_STATUS.get(evaluator, evaluator)
    repair_status = (
        _ZH_REPAIR_STATUS.get(execution.repair_status, execution.repair_status)
        if language == "zh-CN"
        else execution.repair_status
    )
    print(f"{_label('evaluator', language)}{colon} {evaluator}", file=output)
    print(f"{_label('repair', language)}{colon} {repair_status}", file=output)
    print(f"{_label('pipeline', language)}{colon}", file=output)
    for stage in FIRST_FAILURE_LAYERS:
        print(f"  {stage}: {_stage_status(result, stage)}", file=output)

    if show_safe_debug:
        evidence = execution.initial.evidence
        diagnostics = evidence.evaluator_diagnostics
        print(f"{_label('safe_debug', language)}:", file=output)
        print(f"  Provider: {evidence.identity.provider} / {evidence.identity.model}", file=output)
        print(f"  First failure layer: {evidence.first_failure_layer or 'none'}", file=output)
        if evidence.first_failure_layer == "PROVIDER":
            print(
                f"  Provider classification: {evidence.failure_code or 'OTHER_PROVIDER_FAILURE'}",
                file=output,
            )
        if evidence.first_failure_layer == "IR_PARSE":
            print(
                f"  Parse classification: {evidence.failure_code or 'OTHER_IR_PARSE'}",
                file=output,
            )
        print(f"  Request characters: {evidence.request_metrics.get('total_chars', 0)}", file=output)
        print(f"  Provider calls: {provider.calls if provider is not None else 'not exposed'}", file=output)
        if diagnostics is not None:
            print(
                "  Diagnostics: "
                f"dimensions={','.join(diagnostics.dimensions) or 'none'}; "
                f"categories={','.join(diagnostics.categories) or 'none'}; "
                f"findings={diagnostics.finding_count}",
                file=output,
            )


def _credential_status(output: TextIO) -> bool:
    configured = bool(os.environ.get("NPC_LLM_API_KEY", "").strip())
    print(f"NPC_LLM_API_KEY={'SET' if configured else 'MISSING'}", file=output)
    if not configured:
        print(
            "Set NPC_LLM_API_KEY before running the live playground. "
            "The key value is never displayed.",
            file=output,
        )
    return configured


def _prompt_choice(label: str, choices: tuple[str, ...], input_fn: Callable[[str], str], output: TextIO) -> str:
    print(f"{label} choices: {', '.join(choices)}", file=output)
    while True:
        value = input_fn(f"{label}: ").strip()
        if value.isdigit() and 1 <= int(value) <= len(choices):
            return choices[int(value) - 1]
        if value in choices:
            return value
        print("Please choose one of the listed values.", file=output)


def _prompt_requirement(input_fn: Callable[[str], str], output: TextIO) -> str:
    print("Requirement (multi-line; submit an empty line to finish):", file=output)
    lines: list[str] = []
    while True:
        line = input_fn("")
        if not line:
            break
        lines.append(line)
    return "\n".join(lines).strip()


def main(
    argv: list[str] | None = None,
    *,
    input_fn: Callable[[str], str] = input,
    output: TextIO | None = None,
    provider_factory: Callable[[str], HybridProvider] | None = None,
) -> int:
    if output is None:
        output = sys.stdout
    parser = argparse.ArgumentParser(description="Manual Skill Design v1 interactive playground")
    parser.add_argument("--role", choices=ROLE_CHOICES)
    parser.add_argument("--mode", choices=MODE_CHOICES)
    parser.add_argument("--prompt", help="single-line requirement; omit for multi-line input")
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Model used by the configured provider. Default: {DEFAULT_MODEL}",
    )
    parser.add_argument(
        "--language",
        choices=OUTPUT_LANGUAGE_CHOICES,
        default="auto",
        help="Language for human-readable skill text. auto follows Chinese/English user input.",
    )
    parser.add_argument("--show-safe-debug", action="store_true")
    args = parser.parse_args(argv)

    try:
        role = args.role or _prompt_choice("Role", ROLE_CHOICES, input_fn, output)
        mode = args.mode or _prompt_choice("Mode", MODE_CHOICES, input_fn, output)
        requirement = args.prompt.strip() if args.prompt else _prompt_requirement(input_fn, output)
        if not requirement:
            print("Requirement must not be empty.", file=output)
            return 2
        language = resolve_output_language(args.language, requirement)
        if provider_factory is None and not _credential_status(output):
            return 2
        factory = provider_factory or (
            lambda selected_model: _default_hybrid_provider_factory(model=selected_model)
        )
        provider = factory(args.model)

        def decide() -> bool:
            answer = input_fn("Evaluator FAIL. Repair adds one model call. Continue? [Y/n] ").strip().lower()
            return answer not in {"n", "no"}

        execution = execute_playground(
            provider,
            role,
            mode,
            requirement,
            model=args.model,
            language=language,
            repair_decider=decide,
        )
        render_result(
            execution,
            role,
            mode,
            language=language,
            show_safe_debug=args.show_safe_debug,
            provider=provider,
            output=output,
        )
        return 0 if _evaluator_label(execution.final) == "PASS" else 1
    except (KeyboardInterrupt, EOFError):
        print("\nPlayground cancelled.", file=output)
        return 130
    except HybridProviderInvocationError:
        print("Playground failed: provider unavailable (timeout or transport failure).", file=output)
        return 1
    except Exception as error:  # noqa: BLE001
        print(f"Playground failed: {type(error).__name__}.", file=output)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
